use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub(super) struct ArtifactPaths {
    pub(super) source_markdown_path: PathBuf,
    pub(super) source_raw_ocr_markdown_path: PathBuf,
    pub(super) source_json_rebuilt_markdown_path: PathBuf,
    pub(super) source_md_cleanup_markdown_path: PathBuf,
    pub(super) source_ocr_layout_raw_path: PathBuf,
    pub(super) source_ocr_structure_raw_path: PathBuf,
    pub(super) source_layouts_path: PathBuf,
    pub(super) source_toc_path: PathBuf,
    pub(super) source_blocks_path: PathBuf,
    pub(super) source_images_map_path: PathBuf,
    pub(super) front_matter_path: PathBuf,
    pub(super) source_front_matter_path: PathBuf,
    pub(super) translated_front_matter_path: PathBuf,
    pub(super) source_images_dir: PathBuf,
    pub(super) output_markdown_path: PathBuf,
    pub(super) output_html_path: PathBuf,
    pub(super) translated_epub_path: PathBuf,
    pub(super) bilingual_epub_path: PathBuf,
    pub(super) translated_chunks_path: PathBuf,
    pub(super) translated_blocks_path: PathBuf,
    pub(super) translated_toc_path: PathBuf,
    pub(super) checkpoint_path: PathBuf,
    pub(super) checkpoint_wal_path: PathBuf,
    pub(super) manifest_path: PathBuf,
    pub(super) event_log_path: PathBuf,
    pub(super) validation_report_path: PathBuf,
    pub(super) glossary_path: PathBuf,
    pub(super) metrics_path: PathBuf,
    pub(super) llm_route_profile_path: PathBuf,
    pub(super) style_profile_path: PathBuf,
    pub(super) ner_glossary_path: PathBuf,
}

impl ArtifactPaths {
    pub(super) fn new(artifact_dir: &Path) -> Self {
        Self {
            source_markdown_path: artifact_dir.join("source.md"),
            source_raw_ocr_markdown_path: artifact_dir.join("source_raw_ocr.md"),
            source_json_rebuilt_markdown_path: artifact_dir.join("source_json_rebuilt.md"),
            source_md_cleanup_markdown_path: artifact_dir.join("source_md_cleanup.md"),
            source_ocr_layout_raw_path: artifact_dir.join("source_ocr_layout_raw.json"),
            source_ocr_structure_raw_path: artifact_dir.join("source_ocr_structure_raw.json"),
            source_layouts_path: artifact_dir.join("source_layouts.json"),
            source_toc_path: artifact_dir.join("source_toc.json"),
            source_blocks_path: artifact_dir.join("source_blocks.json"),
            source_images_map_path: artifact_dir.join("source_images.json"),
            front_matter_path: artifact_dir.join("front_matter.json"),
            source_front_matter_path: artifact_dir.join("front_matter_source_en.json"),
            translated_front_matter_path: artifact_dir.join("front_matter_translated_zh.json"),
            source_images_dir: artifact_dir.join("imgs"),
            output_markdown_path: artifact_dir.join("translated.md"),
            output_html_path: artifact_dir.join("translated.html"),
            translated_epub_path: artifact_dir.join("packed").join("book_zh.epub"),
            bilingual_epub_path: artifact_dir.join("packed").join("book_bilingual.epub"),
            translated_chunks_path: artifact_dir.join("translated_chunks.json"),
            translated_blocks_path: artifact_dir.join("translated_blocks.json"),
            translated_toc_path: artifact_dir.join("translated_toc.json"),
            checkpoint_path: artifact_dir.join("checkpoint.json"),
            checkpoint_wal_path: artifact_dir.join("checkpoint.wal.ndjson"),
            manifest_path: artifact_dir.join("manifest.json"),
            event_log_path: artifact_dir.join("events.ndjson"),
            validation_report_path: artifact_dir.join("validation_report.json"),
            glossary_path: artifact_dir.join("glossary.json"),
            metrics_path: artifact_dir.join("metrics.json"),
            llm_route_profile_path: artifact_dir.join("llm_route_profiles.json"),
            style_profile_path: artifact_dir.join("style_profile.json"),
            ner_glossary_path: artifact_dir.join("ner_glossary.json"),
        }
    }
}
